### ISSUE TITLE
improve installation user experience

### ISSUE THREAD

**Issue by TomasTomecek** [fedora-modularity/conu#103]
When people install conu from PyPI, there is no way to install addition non-PyPI dependencies. Here is my proposal:

* [x] ~~on centos, remove hard deps on atomic~~ fixed by item below
* [x] on centos, use python-docker-py (version 1) (covered by https://github.com/fedora-modularity/conu/issues/106) #130
* [x] have a test which verifies that conu works on centos7 #130
* [x] for fedora: set the dependencies as `Recommends` #130
* [x] if the required binaries are not available on the system, and the user is requesting a functionality which needs those, exit with a exc saying that the binary is not available and suggest installing a package #126
* [x] ~~if it's possible, print a message when installing from PyPI saying that this lib requires additional dependencies (=binaries)~~ https://github.com/pypa/pip/issues/2933
* [x] write tests which will execute test suite in target environment (start centos7 container, install conu from {pypi,local rpm}, run test suite) #128
